### ISSUE TITLE
Module import error 

### ISSUE THREAD

**Issue by ashwinprasadme** [tpm2-software/tpm2-pytss#25]
I have installed pytss using pip from the master branch. I'm trying to run a simple example. I'm getting a module import error like below.

``` python
>>> from tpm2_pytss.binding import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/pytss/tpm2-pytss/tpm2_pytss/binding.py", line 9, in <module>
    from . import exceptions
  File "/pytss/tpm2-pytss/tpm2_pytss/exceptions.py", line 7, in <module>
    from .esys_binding import (
ModuleNotFoundError: No module named 'tpm2_pytss.esys_binding'
````

**Comment by pdxjohnny** [comment]
It looks like the bindings we're compiled. Did the install complete successfully?

**Comment by Superhepper** [comment]
I just have a question. Which method did you use to install it?

**The following does not work**
`$ python3 -m pip install git+https://github.com/tpm2-software/tpm2-pytss`
because pip does not support the fact that this tpm2-pytss have a submodule.


If you clone the repo and install it that way then you need to add the --recurse-submodules flag when you clone it.
`git clone https://github.com/tpm2-software/tpm2-pytss.git --recurse-submodules`

If you do not add the flag then the swig directory will just be empty.

**Comment by ashwinprasadme** [comment]
Thank you @Superhepper, I was able to get it working by installing directly from the repo as you suggested.  Should this be reflected in the ddocumentation?

```
git clone --depth 1 -b ${tpm2_pytss_version} https://github.com/tpm2-software/tpm2-pytss.git --recurse-submodules && \
    cd tpm2-pytss && \
    python3 setup.py install
```

**Comment by pdxjohnny** [comment]
Thank you, I'll update the docs.

Also, it looks like the most recent version of `pip` does clone with the `--recurse-submodules` flag, which results in compilation.

However, for anyone that find this issue from trying to install with the `git+` URL to `pip`, that for some reason results in the `{_esys,_fapi}_binding.so` files being generated, without their usual `{esys,fapi}_binding.py` counterparts (which are necessary).
