### ISSUE TITLE
Add TCTI

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-pytss#55]
Add the TCTI API

**Comment by joholl** [comment]
Currently, the ESAPI `__init__()` function expects a `TctiLdr` instance (or to be more specific, a python object with a`.ctx` attribute. This `.ctx` is the actual TCTI cdata object.

https://github.com/tpm2-software/tpm2-pytss/blob/07a92e9fa75548ea102ce90b3b6182093b3f7a73/tpm2_pytss/ESAPI.py#L64-L71

We should expect the TCTI cdata context directly. This way, the user can not only pass TctiLdr instances, but also TCTI instances.

Because I could not pass a TCTI object directly, I needed to use an awkward workaround in the FAPI tests in #54, for now.

```python
    @pytest.fixture
        def esys(self):
            # TODO ESAPI should accept either a cdata obj or a dedicated TCTI class, not TctiLdr!
            tcti = SimpleNamespace()
            tcti.ctx = self.fapi.tcti
            with ESAPI(tcti=tcti) as esys:
                yield esys
``

**Comment by whooo** [comment]
I suspect this issue can be closed now
